### ISSUE TITLE
changes made in listener not reflected in UI

### ISSUE THREAD

**Issue by darkbcx** [EddyVerbruggen/nativescript-plugin-firebase#329]
the changes I made in component not reflecting in UI. but it shows when i try to `console.log` it
```
	ngOnInit() {
		firebase.addValueEventListener(
			(result) => {
				console.log("Value: " + JSON.stringify(result.value));
				this.users = result.value;
				console.log('this.users : ', this.users);
				this.test++;
			}, "/users").then(
			(listenerWrapper) => {
				var path = listenerWrapper.path;
				var listeners = listenerWrapper.listeners; // an Array of listeners added
				// you can store the wrapper somewhere to later call 'removeEventListeners'
			});
	}
```

i try to use ngZone but the app crashed.
```
		firebase.addValueEventListener(
			(result) => {
				console.log("Value: " + JSON.stringify(result.value));
				this.zone.run(() => {
					this.users = result.value;
					console.log('this.users : ', this.users);
					this.test++;
				})
			}, "/users").then(
			(listenerWrapper) => {
				var path = listenerWrapper.path;
				var listeners = listenerWrapper.listeners; // an Array of listeners added
				// you can store the wrapper somewhere to later call 'removeEventListeners'
			});
```

with error message like this
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onDataChange failed

[object Object]
File: "file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subscriber.js, line: 227, column: 12

StackTrace: 
  Frame: function:'SafeSubscriber.__tryOrUnsub', file:'file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subscriber.js', line: 227, column: 13
  Frame: function:'SafeSubscriber.next', file:'file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subscriber.js', line: 172, column: 22
  Frame: function:'Subscriber._next', file:'file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subscriber.js', line: 125, column: 26
  Frame: function:'Subscriber.next', file:'file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subscriber.js', line: 89, column: 18
  Frame: function:'Subject.next', file:'file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subject.js', line: 55,
```
